# -*- coding: utf-8 -*-
"""
montar_suplementos_20260925.py

Gera os arquivos auxiliares do pacote de submissao ao Social Science & Medicine:
  01_Title_page.docx, 03_Highlights.docx, 04_Supplementary_material.docx,
  05_Cover_letter.docx, Supplementary_data_strata.xlsx
Depende de montar_manuscrito_en_20260925 (que gera 02_Manuscript_blinded.docx e as contagens).
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import montar_manuscrito_en_20260925 as B
from montar_manuscrito_en_20260925 import *   # noqa

B.main()                       # (re)gera o manuscrito cego e preenche WC/USED
TOTAL = sum(B.WC.values())
MAIN_ONLY = B.WC["main"]

# ---------------------------------------------------------------- suplemento
def build_supplement():
    d = new_doc(spacing=1.15, size=10)
    p = d.add_paragraph(); r = p.add_run("Supplementary material"); r.bold = True; r.font.size = Pt(14)
    p = d.add_paragraph(); rich(p, "Intersectional inequalities in household food insecurity in Brazil: additive, multiplicative and multilevel evidence from a national survey, 2023", size=11)
    para(d, "All tables are generated by the scripts listed at the end from the derived tables; no value was typed by hand. Risk ratios are from Poisson regression with robust variance, survey weights and standard errors clustered on primary sampling units unless stated.", bucket="decl")

    # ---- STROBE
    S = [
        ("1a", "Study design indicated in title or abstract", "Abstract (cross-sectional)"),
        ("1b", "Informative and balanced abstract", "Abstract"),
        ("2", "Scientific background and rationale", "Section 1"),
        ("3", "Objectives, including hypotheses", "Section 1 (last two paragraphs)"),
        ("4", "Key elements of study design", "Section 2.1"),
        ("5", "Setting, locations, relevant dates", "Section 2.1 (fourth quarter 2023, Brazil)"),
        ("6", "Eligibility criteria, sources and selection of participants", "Section 2.1"),
        ("7", "Outcomes, exposures, confounders, effect modifiers, definitions", "Sections 2.2–2.3"),
        ("8", "Data sources and measurement for each variable", "Sections 2.2–2.3"),
        ("9", "Efforts to address potential bias", "Sections 2.4, 4.6"),
        ("10", "How the study size was arrived at", "Section 2.1 (all eligible households)"),
        ("11", "How quantitative variables were handled", "Section 2.3"),
        ("12a", "Statistical methods, including confounding control", "Section 2.4"),
        ("12b", "Methods for subgroups and interactions", "Section 2.4"),
        ("12c", "How missing data were addressed", "Section 2.1 (no missing data on analysed variables)"),
        ("12d", "Account for sampling strategy (cross-sectional)", "Section 2.4 (weights, clustering)"),
        ("12e", "Sensitivity analyses", "Sections 2.4, 3.3, 3.7; Supplementary Tables S2, S3, S8"),
        ("13", "Numbers of participants at each stage", "Section 2.1"),
        ("14", "Characteristics of participants", "Table 1"),
        ("15", "Outcome data", "Table 1"),
        ("16", "Unadjusted and adjusted estimates, precision", "Tables 2–5"),
        ("17", "Other analyses (subgroups, interactions, sensitivity)", "Sections 3.3–3.7; Supplementary tables"),
        ("18", "Key results with reference to objectives", "Section 4.1"),
        ("19", "Limitations, bias and imprecision", "Section 4.6"),
        ("20", "Cautious overall interpretation", "Sections 4.2–4.5"),
        ("21", "Generalisability", "Sections 4.6 (single quarter; Brazilian setting)"),
        ("22", "Funding", "Title page"),
    ]
    caption(d, "**Supplementary Table S1.** STROBE checklist for cross-sectional studies, with location in the manuscript.")
    table(d, ["Item", "Recommendation", "Location"], [list(x) for x in S], widths=[1.2, 8.5, 6.0], font=8)

    # ---- S5 celulas, IC delta vs bootstrap, decomposicao
    f1b = pd.read_csv(D16 / "interseccional_2023.csv"); f2b = pd.read_csv(D16 / "interseccional_2023_parte2.csv"); f3b = pd.read_csv(D16 / "interseccional_2023_parte3.csv")
    bt = {}
    any_rows = f1b[f1b.desfecho == "ia_total"].reset_index(drop=True)
    sev_rows = f2b[f2b.parte == "a_nacional_grave"].reset_index(drop=True)
    for k, i in [("sex", 0), ("edu", 1), ("inc", 2)]:
        bt[(k, "ia_total")] = (any_rows.loc[i, "reri_ic95_low"], any_rows.loc[i, "reri_ic95_high"])
        bt[(k, "ia_grave")] = (sev_rows.loc[i, "reri_ic95_low"], sev_rows.loc[i, "reri_ic95_high"])
    bt[("res", "ia_total")] = (f3b.loc[0, "reri_ic95_low"], f3b.loc[0, "reri_ic95_high"])
    bt[("res", "ia_grave")] = (f3b.loc[1, "reri_ic95_low"], f3b.loc[1, "reri_ic95_high"])
    rows = []
    for k, lab_ in [("sex", "Race × sex"), ("edu", "Race × education"), ("inc", "Race × income"), ("res", "Race × residence")]:
        for dd, dl in [("ia_total", "Any"), ("ia_grave", "Severe")]:
            r = PAIR(k, dd); jt, a, b, it = jd(k, dd)
            rows.append([lab_ if dl == "Any" else "", dl, f"{f1(r.p00)} / {f1(r.p10)} / {f1(r.p01)} / {f1(r.p11)}",
                         f"{n0(r.n00)} / {n0(r.n10)} / {n0(r.n01)} / {n0(r.n11)}", est_ci_short(r.reri, r.reri_lo_delta, r.reri_hi_delta),
                         ci(*bt[(k, dd)]), f"{f1(jt)} = {f1(a)} + {f1(b)} + {f1(it)}", f1(it / jt * 100)])
    caption(d, "**Supplementary Table S2.** Prevalence (%) and households in the four joint categories (reference / Black only / other only / both); RERI with delta-method and cluster-bootstrap 95% CI; and decomposition of the joint disparity in percentage points into race alone, other characteristic alone and interaction (excess intersectional disparity), with the interaction share (%).")
    table(d, ["Pair", "Outcome", "Prevalence (%): ref / Black / other / both", "Households: ref / Black / other / both", "RERI, delta (95% CI)", "RERI, bootstrap 95% CI", "Joint disparity = race + other + interaction (pp)", "Interaction share (%)"], rows, font=7.5)

    # ---- S1 regiao
    rg = reg[reg.parte == "b_regional"]
    nm = {"Norte": "North", "Nordeste": "Northeast", "Centro-Oeste": "Central-West", "Sudeste": "Southeast", "Sul": "South"}
    rows = []
    for r in rg.itertuples():
        rows.append([nm[r.regiao], "Any" if r.desfecho == "ia_total" else "Severe", n0(r.n_total_celula),
                     f2(r.rr10), f2(r.rr01), f2(r.rr11), est_ci_short(r.reri, r.reri_ic95_low, r.reri_ic95_high), f2(r.razao_razoes)])
    caption(d, "**Supplementary Table S3.** Race × sex (woman) by macro-region: risk ratios, RERI with cluster-bootstrap 95% CI (300 replicates) and ratio of risk ratios.")
    table(d, ["Region", "Outcome", "Households", "RR Black only", "RR woman only", "RR both", "RERI (95% CI)", "Ratio of RRs"], rows, font=8)

    # ---- S3 tripla
    rows = [[{"renda_q1": "Race × sex × income ≤1/4 MW", "sem_fund": "Race × sex × no schooling/incomplete primary"}[r.terceira_dimensao],
             "Any" if r.desfecho == "ia_total" else "Severe", est_ci_short(r.rr, r.lo, r.hi), pfmt(r.p)] for r in t7.itertuples()]
    caption(d, "**Supplementary Table S4.** Three-way interaction terms (ratio of risk ratios) in models with all lower-order terms.")
    table(d, ["Term", "Outcome", "Ratio of RRs (95% CI)", "p"], rows, font=8)

    # ---- S2 estratos
    rows = []
    lab = {"negra": "Black race", "mulher": "Woman"}
    strat = {"renda": "Income band", "instrucao": "Education", "raca": "Race"}
    for r in t6.itertuples():
        rows.append([lab[r.exposicao], strat[r.estratificado_por], LAB1.get(r.estrato, r.estrato.replace("_", " ")), "Any" if r.desfecho == "ia_total" else "Severe",
                     n0(r.n), f"{f1(r.prev_exposto)} / {f1(r.prev_nao_exposto)}", est_ci_short(r.dif_pp, r.dif_pp_lo, r.dif_pp_hi, 1),
                     est_ci_short(r.rr_ajustado, r.lo, r.hi), pfmt(r.p)])
    caption(d, "**Supplementary Table S5.** Stratum-specific associations of Black race and of woman sex: prevalence in exposed and unexposed (%), absolute difference (percentage points; approximate 95% CI treating groups as independent) and adjusted risk ratio.")
    table(d, ["Exposure", "Stratified by", "Stratum", "Outcome", "n", "Prev. exposed / unexposed", "Difference, pp (95% CI)", "Adjusted RR (95% CI)", "p"], rows, font=7.5)

    # ---- S6 gradiente
    rows = []
    for r in t4.itertuples():
        rows.append(["Any" if r.desfecho == "ia_total" else "Severe", int(r.n_desv), n0(r.nao_negra_n), est_ci_short(r.nao_negra_pct, r.nao_negra_lo, r.nao_negra_hi, 1),
                     n0(r.negra_n), est_ci_short(r.negra_pct, r.negra_lo, r.negra_hi, 1), f1(r.diferenca_pp)])
    caption(d, "**Supplementary Table S6a.** Prevalence of food insecurity (%) by number of disadvantages and race, with the absolute difference (percentage points).")
    table(d, ["Outcome", "Disadvantages", "Non-Black, n", "Non-Black, % (95% CI)", "Black, n", "Black, % (95% CI)", "Difference, pp"], rows, font=8)
    rows = []
    for r in t5.itertuples():
        rows.append(["Any" if r.desfecho == "ia_total" else "Severe", r.escala.replace("relativa", "relative").replace("absoluta", "absolute"),
                     est_ci_short(r.nao_negra, r.nao_negra_lo, r.nao_negra_hi, 2 if "relativa" in r.escala else 1),
                     est_ci_short(r.negra, r.negra_lo, r.negra_hi, 2 if "relativa" in r.escala else 1), pfmt(r.p_diferenca)])
    caption(d, "**Supplementary Table S6b.** Change in food insecurity per additional disadvantage, by race, on relative (risk ratio, Poisson) and absolute (percentage points, linear probability model) scales, and p-value for the difference between slopes.")
    table(d, ["Outcome", "Scale", "Non-Black (95% CI)", "Black (95% CI)", "p (difference)"], rows, font=8)

    # ---- S4 MAIHDA coef
    lab4 = {"(Intercept)": "Intercept (reference stratum)", "raca_catnegra": "Black race", "sexo_catmulher": "Woman",
            "instrucao_catfund_med": "Education: complete primary/incomplete secondary", "instrucao_catmedio_comp": "Education: complete secondary",
            "instrucao_catsem_fund": "Education: no schooling/incomplete primary", "renda_catq1": "Income ≤1/4 MW", "renda_catq2": "Income >1/4–1/2 MW",
            "renda_catq3": "Income >1/2–1 MW", "renda_catq4": "Income >1–2 MW", "rural_catrural": "Rural residence"}
    rows = []
    for t in lab4:
        a = coef("ia_total", t); s_ = coef("ia_grave", t)
        rows.append([lab4[t], est_ci_short(a.oddsr, a.or_lo, a.or_hi), est_ci_short(s_.oddsr, s_.or_lo, s_.or_hi)])
    caption(d, "**Supplementary Table S7.** MAIHDA Model B fixed effects: odds ratios (95% CI). Reference: non-Black man, tertiary education, income >2 MW, urban.")
    table(d, ["Term", "Any food insecurity", "Severe food insecurity"], rows, font=8)
    ma, mg = M["ia_total"], M["ia_grave"]
    rows = [["Unweighted (main analysis): VPC null, %", f1(ma.vpc_nulo * 100), f1(mg.vpc_nulo * 100)],
            ["Unweighted: VPC main-effects model, %", f1(ma.vpc_B * 100), f1(mg.vpc_B * 100)],
            ["Unweighted: PCV, %", f1(ma.pcv * 100), f1(mg.pcv * 100)],
            ["Approximate weights: VPC null, %", f1(ma.w_vpc_nulo * 100), f1(mg.w_vpc_nulo * 100)],
            ["Approximate weights: VPC main-effects model, %", f1(ma.w_vpc_B * 100), f1(mg.w_vpc_B * 100)],
            ["Approximate weights: PCV, %", f1(ma.w_pcv * 100), f1(mg.w_pcv * 100)]]
    caption(d, "**Supplementary Table S8.** Sensitivity of MAIHDA variance measures to approximate (normalised) survey weights. The weighted fits are not design-consistent.")
    table(d, ["Measure", "Any food insecurity", "Severe food insecurity"], rows, font=8)

    # ---- Fig S1
    figure(d, "figS1_race_gaps_education.png", 6.0, "**Supplementary Fig. S1.** Racial gap in food insecurity across education categories. Adjusted risk ratio (a, c; adjusted for sex, income and residence) and absolute difference in prevalence (b, d; crude) for Black versus non-Black reference persons, for any (a, b) and severe (c, d) food insecurity. Bars are 95% confidence intervals.")

    para(d, "Reproducibility. Scripts: analise_consolidada_artigo3_20260925.py (Tables 1–4 and Supplementary Tables S2–S6); maihda_v2_20260925.R (Table 5 and Supplementary Tables S7–S8); figuras_artigo3_20260925.py (figures); montar_manuscrito_en_20260925.py (manuscript, reading every number from the derived tables). Derived tables are in dados/v2_20260925. Supplementary data file: Supplementary_data_strata.xlsx (160 strata).", bucket="decl")
    d.save(OUT / "04_Supplementary_material.docx")


# ---------------------------------------------------------------- title page
def build_title_page():
    d = new_doc(spacing=1.3, size=11)
    p = d.add_paragraph(); r = p.add_run("Title page (not for blinded review)"); r.italic = True; r.font.size = Pt(9)
    p = d.add_paragraph(); r = p.add_run("Intersectional inequalities in household food insecurity in Brazil: additive, multiplicative and multilevel evidence from a national survey, 2023"); r.bold = True; r.font.size = Pt(15)
    para(d, "**Running title:** Intersectional food insecurity in Brazil", bucket="decl")
    para(d, "**Authors:** [Bernardo Castanho and co-authors, in final order; to be completed]", bucket="decl")
    para(d, "**Affiliations:** [to be completed]", bucket="decl")
    para(d, "**ORCID:** [required for the CAPES open-access agreement; link each author's ORCID to “Meus Dados CAPES”]", bucket="decl")
    para(d, "**Corresponding author:** [name, institutional address, e-mail]", bucket="decl")
    para(d, f"**Manuscript length (Social Science & Medicine limit 9,000 words including abstract, tables, figure captions and references):** {n0(TOTAL)} words in total, of which main text {n0(MAIN_ONLY)}, abstract and keywords {n0(B.WC['abstract'])}, tables {n0(B.WC['tables'])}, captions {n0(B.WC['captions'])}, references {n0(B.WC['refs'])}, declarations {n0(B.WC['decl'])}. Five tables and four figures; supplementary material provided separately.", bucket="decl")
    para(d, "**Acknowledgements:** [to be completed]", bucket="decl")
    para(d, "**Funding:** [to be completed; state funder and grant number, or “This research received no specific funding”]", bucket="decl")
    para(d, "**Declaration of competing interest:** [to be completed by all authors]", bucket="decl")
    para(d, "**Ethics:** publicly available, anonymised secondary data; not subject to ethics committee review under Resolution CNS 510/2016 [confirm with institution].", bucket="decl")
    para(d, "**CRediT author statement:** [to be completed: Conceptualization; Methodology; Software; Formal analysis; Investigation; Data curation; Writing – original draft; Writing – review & editing; Visualization; Supervision]", bucket="decl")
    para(d, f"**Declaration of generative AI and AI-assisted technologies in the writing process:** {AI_STATEMENT}", bucket="decl")
    d.save(OUT / "01_Title_page.docx")


def build_highlights():
    d = new_doc(spacing=1.3, size=12)
    p = d.add_paragraph(); r = p.add_run("Highlights"); r.bold = True; r.font.size = Pt(14)
    for h in HIGHLIGHTS:
        p = d.add_paragraph(style="List Bullet"); p.add_run(h)
    p = d.add_paragraph(); rich(p, "*(Elsevier limit: 3–5 bullet points, maximum 85 characters each, including spaces.)*", size=9)
    d.save(OUT / "03_Highlights.docx")


def build_cover_letter():
    d = new_doc(spacing=1.25, size=11)
    for t in ["[Date]", "", "The Editors", "Social Science & Medicine", "",
              "Dear Editors,", "",
              f"We submit “Intersectional inequalities in household food insecurity in Brazil: additive, multiplicative and multilevel evidence from a national survey, 2023” for consideration as an original research article.",
              "",
              f"Whether the joint disadvantage of race, gender, education, income and place is “more than the sum of its parts” is a recurring question in quantitative intersectionality research, and the answer depends on the scale of analysis. Using {n0(NA)} households from the 2023 Brazilian national household survey, we combine additive-scale interaction (RERI), multiplicative-scale interaction, the joint-disparity decomposition, cumulative-disadvantage gradients and intersectional multilevel analysis of individual heterogeneity and discriminatory accuracy (MAIHDA) across 160 strata.",
              "",
              f"Three findings matter for the journal's readers. First, intersectional inequality in food insecurity is large (predicted prevalence from {f1(lo_any.p_completo*100)}% to {f1(hi_any.p_completo*100)}% across strata) yet, on the logit scale, almost entirely additive ({f1(M['ia_total'].pcv*100)}% of between-strata variance explained by main effects) and dominated by income. Second, joint effects are super-additive but sub-multiplicative, so conclusions about synergy reverse with the scale unless both are reported and benchmarked. Third, the racial gap widens in relative terms and narrows in absolute terms as income rises, consistent with diminished returns.",
              "",
              "The paper builds directly on work published in this journal on intersectionality in population health research, on the additive and multiplicative scales of interaction, and on MAIHDA, and extends it to a low- and middle-income setting and a food-security outcome, where quantitative intersectional evidence is scarce.",
              "",
              "The manuscript is not under consideration elsewhere. All data are public. A blinded manuscript, title page, highlights and supplementary material are enclosed. Generative AI was used in the preparation of the work and is declared in the manuscript and title page. We would be glad to provide code and derived tables on request.",
              "", "Sincerely,", "[Corresponding author name, affiliation, e-mail]", "",
              "Suggested reviewers: [to be completed by the authors]", "Reviewers to exclude: [to be completed, if any]"]:
        p = d.add_paragraph(t); p.paragraph_format.space_after = Pt(4)
    d.save(OUT / "05_Cover_letter.docx")


def build_xlsx():
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment
    wb = openpyxl.Workbook(); ws = wb.active; ws.title = "README"
    lines = ["Supplementary data: the 160 intersectional strata (PNADC 2023, Q4).",
             "Strata are the cross-classification of race (2) x sex (2) x education (4) x income (5) x residence (2).",
             "Predicted probabilities come from logistic multilevel models (lme4): 'null' = Model A with empirical-Bayes shrinkage; 'additive' = Model B main effects only; 'full' = Model B main effects + stratum residual.",
             "u = Model B stratum residual (log-odds); se_u = conditional standard error; z = u/se_u. About 5% of strata are expected to exceed |z| = 1.96 by chance.",
             "obs_unweighted / obs_weighted = observed prevalence in the stratum (weighted uses the survey weight). MAIHDA models are unweighted.",
             "Labels: Race N = non-Black, B = Black; Education: 'no schooling/incomplete primary', 'complete primary/incomplete secondary', 'complete secondary', 'tertiary'; Income in minimum wages per capita."]
    for i, l in enumerate(lines, 1): ws.cell(i, 1, l)
    ws.column_dimensions["A"].width = 150
    lab = {"nao_negra": "Non-Black", "negra": "Black", "homem": "Man", "mulher": "Woman", "sem_fund": "No schooling/incomplete primary",
           "fund_med": "Complete primary/incomplete secondary", "medio_comp": "Complete secondary", "superior": "Tertiary", "q1": "<=1/4", "q2": ">1/4-1/2",
           "q3": ">1/2-1", "q4": ">1-2", "mais_2sm": ">2", "urbano": "Urban", "rural": "Rural"}
    for dd, nome in [("ia_total", "Any food insecurity"), ("ia_grave", "Severe food insecurity")]:
        w = wb.create_sheet(nome)
        hdr = ["Race", "Sex", "Education", "Income (MW)", "Residence", "n", "obs_unweighted", "obs_weighted", "pred_null_shrunk", "pred_additive", "pred_full", "u", "se_u", "z"]
        w.append(hdr)
        s = m3[m3.desfecho == dd].sort_values("p_completo", ascending=False)
        for r in s.itertuples():
            parts = r.estrato.split("__")
            w.append([lab.get(parts[0], parts[0]), lab.get(parts[1], parts[1]), lab.get(parts[2], parts[2]), lab.get(parts[3], parts[3]), lab.get(parts[4], parts[4]),
                      int(r.n), round(r.obs_naoponderada, 4), round(r.obs_ponderada, 4), round(r.p_nulo_shrunk, 4), round(r.p_aditivo, 4), round(r.p_completo, 4),
                      round(r.u, 4), round(r.se_u, 4), round(r.z, 2)])
        for c in w[1]: c.font = Font(bold=True); c.fill = PatternFill("solid", fgColor="E7E6E6"); c.alignment = Alignment(wrap_text=True)
        for col, wd in zip("ABCDEFGHIJKLMN", [11, 8, 36, 12, 10, 8, 14, 13, 16, 14, 11, 9, 9, 8]): w.column_dimensions[col].width = wd
        w.freeze_panes = "A2"
    wb.save(OUT / "Supplementary_data_strata.xlsx")


if __name__ == "__main__":
    build_supplement(); build_title_page(); build_highlights(); build_cover_letter(); build_xlsx()
    print("arquivos gerados em", OUT)
    for f in sorted(OUT.glob("*")):
        if f.is_file(): print("  ", f.name, f.stat().st_size // 1024, "KB")
